### ISSUE TITLE
[webpack team proposal] Webpack build time improvements

### ISSUE THREAD

**Issue by jhnns** [JSKongress/JS-Kongress-Munich-In-Deep-Track#11]
**Session Title:**
Webpack build time improvements

**Session Abstract:**
Building large web applications with webpack can be cumbersome because of long build times. We (the webpack team) have heard of build times between 2-3 minutes or even more. Airbnb, for instance, is struggling with a build time of about 3 minutes (https://github.com/webpack/webpack/issues/5718). During this session, we can talk about the current bottlenecks and how it can improved.

**Approximate Duration:** 
60 minutes

**Your Name:**
Johannes Ewald

**Your Twitter handle:**
jhnnns

**Requirements:**
[ ] No
[x] Yes => I think it would be helpful to inspect a flame graph of a webpack build to show/demonstrate the bottlenecks. So we would need a projector with HDMI jack.

**Complexity:**
[x] Advanced
[ ] Intermediate
[ ] Beginner

**Other information:**
Maybe more flame graphs from different projects?

**Comment by bmeurer** [comment]
I'm curious to hear about potential things that can be done on the V8 side. Also interesting to learn which Node versions are being used. Since we're actively working on tooling performance, it'd be interesting to hear whether folks are actually using the latest Node versions or stuck at rather old Node versions.

**Comment by gdborton** [comment]
If you need anything from us (.cpuprofile, stats, basic config, etc) for this just let me know.

**Comment by jhnns** [comment]
Actually, a .cpuprofile and a basic configuration (node version for @bmeurer 😁 , webpack version, webpack loaders and webpack plugins) would be really really great. You can send it to mail@johannesewald.de if you don't want to put it here. However, the Deep Track at the JS Kongress will be public, just FYI.
