### ISSUE TITLE
Roll it up, shake it out: The future of Rollup.js

### ISSUE THREAD

**Issue by lukastaegert** [JSKongress/JS-Kongress-Munich-In-Deep-Track#17]
**Session Title:**
Roll it up, shake it out: The future of Rollup.js

**Session Abstract:**
Rollup is "the other JavaScript bundler" that has pioneered features such as "tree-shaking" and "scope-hoisting" and has been adopted by popular libraries such as React or Moment.js as their bundling tool. However in the past, tree-shaking has remained an unfulfilled promise in most real-world situations. This is changing now.

As the current main contributor of Rollup, I would like to talk with you about the following:
* Do we really need another bundling tool besides Webpack? :)
* What are the recent tree-shaking improvements all about and what challenges are we facing now? What kind of code is removed easily and where does the algorithm struggle?
* Where should we go next? Possible ideas are untranspiled JSX support (via plugin) or prepack-style source code optimizations but I would really love your input here.
* How can you contribute? Rollup is supported by a fairly small group of people which means YOUR contributions can have a huge impact in moving Rollup forward!

**Approximate Duration:**
60 minutes

**Your Name*:**
Lukas Taegert

**Your Twitter handle*:**
lukastaegert

**Requirements:**

[ ] No
[x] Yes => A projector and a USB-C adapter would help when talking about code samples

**Complexity:**

[ ] Advanced
[x] Intermediate
[x] Beginner

**Other Information:**
Due to time constraints on my side, this session can only take place on Tuesday morning.

**Comment by popeindustries** [comment]
That title is 💥

**Comment by Andarist** [comment]
Please record it if possible :)

**Comment by lukastaegert** [comment]
No recording, unfortunately 😢

Anyway, I have been asked to post the REPL links I used to showcase Rollup's treeshaking, so here they are + some more. BTW if you are not familiar with Rollup, just clicking through the examples built into the REPL is certainly worthwhile!

* [Prominent issues we had in Rollup before this summer](https://rollupjs.org/repl?version=0.48.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGbGliLmpzJyUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJsaWIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIydmFyJTIwdW51c2VkRnVuY3Rpb24lM0IlNUNudW51c2VkRnVuY3Rpb24lMjAlM0QlMjBmdW5jdGlvbigpJTdCJTdEJTNCJTVDbiU1Q252YXIlMjB3aXRoU2lkZUVmZmVjdCUyMCUzRCUyMCU3QndpbmRvdyU3RCUzQiU1Q253aXRoU2lkZUVmZmVjdC53aW5kb3cuZGFuZ2Vyb3VzTXV0YXRpb24lMjAlM0QlMjAnbXV0YXRpb24nJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
* [The state of things today](https://rollupjs.org/repl?version=0.51.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGbGliLmpzJyUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJsaWIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIydmFyJTIwdW51c2VkRnVuY3Rpb24lM0IlNUNudW51c2VkRnVuY3Rpb24lMjAlM0QlMjBmdW5jdGlvbigpJTdCJTdEJTNCJTVDbiU1Q252YXIlMjB3aXRoU2lkZUVmZmVjdCUyMCUzRCUyMCU3QndpbmRvdyU3RCUzQiU1Q253aXRoU2lkZUVmZmVjdC53aW5kb3cuZGFuZ2Vyb3VzTXV0YXRpb24lMjAlM0QlMjAnbXV0YXRpb24nJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
* [We can even  track mutations across reassignments now](https://rollupjs.org/repl?version=0.51.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwVjhFbmdpbmUlMjAoKSUyMCU3QiU3RCU1Q24lNUNuVjhFbmdpbmUucHJvdG90eXBlLnRvU3RyaW5nJTIwJTNEJTIwZnVuY3Rpb24lMjAoKSUyMCU3QiUyMCU1Q24lNUN0cmV0dXJuJTIwJ1Y4JyUzQiU1Q24lN0QlM0IlNUNuJTVDbmZ1bmN0aW9uJTIwVjZFbmdpbmUlMjAoKSUyMCU3QiU3RCU1Q24lNUNuJTJGJTJGJTIwUmVtb3ZlJTIwY29tbWVudCUyMGFuZCUyMHNlZSUyMHdoYXQlMjBoYXBwZW5zJTNBJTVDbiUyRiUyRiUyMFY2RW5naW5lLnByb3RvdHlwZSUyMCUzRCUyMFY4RW5naW5lLnByb3RvdHlwZSUzQiU1Q24lNUNuJTJGJTJGJTIwSWYlMjB5b3UlMjB0aGVuJTIwcmVtb3ZlJTIwdGhpcyUyMG11dGF0aW9uJTJDJTIwVjYlMjB3aWxsJTIwYmUlNUNuJTJGJTJGJTIwdHJlZXNoYWtlbiUyMGFnYWluJTVDblY2RW5naW5lLnByb3RvdHlwZS50b1N0cmluZyUyMCUzRCUyMGZ1bmN0aW9uJTIwKCklMjAlN0IlNUNuJTVDdHJldHVybiUyMCdWNiclM0IlNUNuJTdEJTNCJTVDbiU1Q25jb25zb2xlLmxvZyglMjBuZXclMjBWOEVuZ2luZSgpLnRvU3RyaW5nKCklMjApJTNCJTVDbiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

Other improvements:
* [We can treeshake calls to object literal methods](https://rollupjs.org/repl?version=0.51.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3Qm9iajElMkMlMjBvYmoyJTdEJTIwZnJvbSUyMCcuJTJGbGliLmpzJyUzQiU1Q24lNUNub2JqMS5lZmZlY3QoKSUzQiU1Q25vYmoyLm5vRWZmZWN0KCklM0IlNUNuJTVDbiUyRiUyRiUyMFRoZSUyMG5leHQlMjBjYWxsJTIwd2lsbCUyMG5vdCUyMGJlJTIwcmVtb3ZlZCUyMGJlY2F1c2UlMjBvYmoxJTVDbiUyRiUyRiUyMGlzJTIwYWxyZWFkeSUyMGluY2x1ZGVkLiU1Q24lMkYlMkYlMjBGb3IlMjBpbmNsdWRlZCUyMG9iamVjdHMlMkMlMjB3ZSUyMGNhbm5vdCUyMGJlJTIwc3VyZSUyMCh5ZXQpJTVDbiUyRiUyRiUyMGlmJTIwdGhleSUyMGhhdmUlMjBiZWVuJTIwbXV0YXRlZCUzQSU1Q25vYmoxLm5vRWZmZWN0KCklM0IlNUNuJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxpYi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMG9iajElMjAlM0QlMjAlN0IlNUNuJTVDdGVmZmVjdCUzQSUyMCgpJTIwJTNEJTNFJTIwY29uc29sZS5sb2coJ0hpJTIwSlMlMjBLb25ncmVzcyEnKSUyQyU1Q24lNUN0bm9FZmZlY3QlM0ElMjAoKSUyMCUzRCUzRSUyMCU3QiU3RCU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwb2JqMiUyMCUzRCUyMCU3QiU1Q24lNUN0bm9FZmZlY3QlM0ElMjAoKSUyMCUzRCUzRSUyMCU3QiU3RCU1Q24lN0QlNUNuJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)
* [Side-effect-free functions returned by IIFEs will be removed as well](https://rollupjs.org/repl?version=0.51.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmZuMSU3RCUyMGZyb20lMjAnLiUyRmxpYi5qcyclM0IlNUNuJTVDbmZuMSgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxpYi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGZuMSUyMCUzRCUyMGZ1bmN0aW9uKCklN0IlNUNuJTVDdHJldHVybiUyMCgpJTIwJTNEJTNFJTIwJTdCJTdEJTNCJTVDbiU3RCgpJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by TrySound** [comment]
@lukastaegert Links are localhost

**Comment by lukastaegert** [comment]
Ups, thanks! Should be fixed now!

**Comment by ttraenkler** [comment]
I could have recorded but was asked not to by the organizers - sorry!
Lukas Taegert <notifications@github.com> schrieb am Mi. 15. Nov. 2017 um
06:50:
