### ISSUE TITLE
TC39 -- Immutable values, operator overloading, and custom numeric literals

### ISSUE THREAD

**Issue by littledan** [JSKongress/JS-Kongress-Munich-In-Deep-Track#23]
**Session Title:** Immutable values, operator overloading, and custom numeric literals

**Session Abstract:** Discuss some extremely early ideas in TC39 about extending the language to support various aspects of custom types

**Approximate Duration:** 60

**Your Name*:** Daniel Ehrenberg

**Your Twitter handle*:** littledan

**Requirements:**

[x] No
[ ] Yes => Please share what do you need.

**Complexity:**

[ ] Advanced

[x] Intermediate
[ ] Beginner

**Other information:**

**Comment by chicoxyzzy** [comment]
I can't find repo for Immutable values proposal. Is it public?

**Comment by littledan** [comment]
No, I just made this gist: https://gist.github.com/littledan/eb10cabc39e884c4a5fd6bbaa60afec0 . I hope to have a proper proposal soon!
