### ISSUE TITLE
[V8 team proposal] Lifetime of a JavaScript language feature

### ISSUE THREAD

**Issue by mathiasbynens** [JSKongress/JS-Kongress-Munich-In-Deep-Track#3]
**Session Title:**
Lifetime of a JavaScript language feature

**Session Abstract:**
This session describes what happens from the moment when a feature is proposed to ECMAScript to when it gets fully integrated into the VM.

**Approximate Duration:** 
30 minutes

**Your Name:**
V8 team

**Your Twitter handle:**
v8js

**Requirements:**
[x] No
[ ] Yes => Please share what do you need.

**Complexity:**
[ ] Advanced
[x] Intermediate
[ ] Beginner

**Comment by mathiasbynens** [comment]
cc @littledan

**Comment by littledan** [comment]
Happy to participate in this!

**Comment by gsathya** [comment]
I'll be around for this too.
