### ISSUE TITLE
[V8 team proposal] The future of WebAssembly

### ISSUE THREAD

**Issue by mathiasbynens** [JSKongress/JS-Kongress-Munich-In-Deep-Track#4]
**Session Title:**
The future of WebAssembly

**Session Abstract:**

Discuss current threading proposal:

* Roughly equivalent to SharedArrayBuffer + Web Workers
* Atomics and futexes give native-level performance for low-level concurrency
* Still in “WASM is a machine” style, no new concurrency constructs
* Why is this hard for anything other than low-level shared memory?

Current thinking on integration with the DOM/JS:

* Opaque references to JS objects can flow through WASM code
* Access must be accomplished through imported JavaScript functions

**Approximate Duration:** 
30 minutes

**Your Name:**
Ben Titzer

**Your Twitter handle:**
v8js

**Requirements:**
[x] No
[ ] Yes => Please share what do you need.

**Complexity:**
[ ] Advanced
[x] Intermediate
[x] Beginner

**Comment by mathiasbynens** [comment]
For Nov 13.

**Comment by littledan** [comment]
FWIW I'm starting out getting involved in Wasm; I could come if it is helpful, but nowhere near as much of an expert as Ben.

**Comment by jhnns** [comment]
There's some overlap with #9 but I still think it's better to keep them separated.
