### ISSUE TITLE
[V8 team proposal] Making sure that a new Chrome version does not break your website

### ISSUE THREAD

**Issue by mathiasbynens** [JSKongress/JS-Kongress-Munich-In-Deep-Track#7]
**Session Title:**
Making sure that a new Chrome version does not break your website

**Session Abstract:**

This session describes on how to test your web application in advance in order to find out if future Chrome releases might "break" your web application. The earlier you discover problems, the higher the chance for Chrome and/or you to fix them without impacting your revenue stream.

**Approximate Duration:** 
15–30 minutes

**Your Name:**
V8 team

**Your Twitter handle:**
v8js

**Requirements:**
[x] No
[ ] Yes => Please share what do you need.

**Complexity:**
[ ] Advanced
[ ] Intermediate
[x] Beginner

**Comment by mathiasbynens** [comment]
Possibly in collab with @zoepage!

**Comment by littledan** [comment]
The group could also talk about what Chrome does to try to not break your web page, and how you can help Chrome to not break your page (not sure if this is interesting for people though).

**Comment by natorion** [comment]
@littledan that was the idea.

**Comment by littledan** [comment]
Oh I see, I misinterpreted it to be about how website owners can fix their site for new Chrome versions. Sounds great!
