### ISSUE TITLE
What's coming in TC39? We want your help!

### ISSUE THREAD

**Issue by littledan** [JSKongress/JS-Kongress-Munich-In-Deep-Track#8]
**Session Title:**
What's coming in TC39? We want your help!

**Session Abstract:**
Give an overview of some of the topics under discussion at TC39, where they are in the standards process, and (most importantly) feedback from everyone in the room about what they think. At the end, it would open up to open-ended discussion about what other features should be discussed 

**Approximate Duration:** 
90 minutes

(Yes, this is a bit long, but in previous meetings where I've just gone over just a meeting agenda with various other groups of intelligent engineers, even 90 minutes has not quite been enough time.)

**Your Name:**
Daniel Ehrenberg

**Your Twitter handle:**
littledan

**Requirements:**

[ x ] No
[ ] Yes => Please share what do you need.

**Complexity:**

[ x ] Advanced
[ x ] Intermediate
[ ] Beginner

**Comment by littledan** [comment]
To clarify, I can't speak for all of TC39 here, but many of us definitely want community input. The session would unavoidably include my own views, since it's impossible to be 100% objective about these so rts of things.

**Comment by johannes-weber** [comment]
Possibly in collab with @bterlson?
