### ISSUE TITLE
[webpack team proposal] WASM from developer-perspective

### ISSUE THREAD

**Issue by sokra** [JSKongress/JS-Kongress-Munich-In-Deep-Track#9]
**Session Title:**
WASM from developer-perspective: How make using WASM developer-friendly?

**Session Abstract:**
* How make using WASM developer-friendly?
  * Tooling
  * Devtools
  * Debugging
  * Interop
  * Libraries and Applications

**Approximate Duration:** 
30 minutes

**Your Name:**
Tobias Koppers

**Your Twitter handle:**
wSokra

**Requirements:**

[x] No
[ ] Yes => Please share what do you need.

**Complexity:**

[ ] Advanced

[ ] Intermediate
[x] Beginner

**Other information:**

Motivation: Figure out what's needed to make WASM more approachable.

**Comment by bmeurer** [comment]
Thoughts on integration of the existing Node/webpack/NPM infrastructure with emscripten based tooling would be highly interesting.

cc @mathiasbynens @titzer @gahaas

**Comment by mathiasbynens** [comment]
Also things like https://github.com/glimmerjs/glimmer-vm/pull/719/commits/83166bea2b96d3846c8683d0a789fcb8f8c86901
